#### Họ tên: Đàm Tử Tâm
#### MSSV: 21120551
#### Môn: Toán ứng dụng & thống kê
#### Lớp: 21_2

#### Đồ án 2:

#### Giải thuật:

Giải thuật tìm ma trận nghịch đảo $A^{-1}$  bằng phép khử Gauss-Jordan sẽ sử dụng các phép biến đổi ma trận để chuyển ma trận A thành ma trận đơn vị I. Sau đó, áp dụng cùng các biến đổi đó vào ma trận đơn vị I, ta thu được ma trận nghịch đảo $A^{-1}$.

Cụ thể, giải thuật được thực hiện như sau:

- Bước 1: Tạo ma trận bổ sung A' bằng cách ghép ma trận đơn vị I vào bên phải của ma trận A.

- Bước 2: Áp dụng phép khử Gauss - Jordan vào ma trận bổ sung A' để chuyển ma trận A thành ma trận bậc thang. Lưu ý rằng phép khử Gauss-Jordan được áp dụng đồng thời vào cả ma trận A và I.

- Bước 3: Áp dụng phép biến đổi đến ma trận bậc thang A' để chuyển ma trận A thành ma trận đơn vị I.

- Bước 4: Ma trận đơn vị I' mới thu được sau các phép biến đổi trong bước 2 là ma trận nghịch đảo của ma trận A. Tức là I' chính là ma trận $A^{-1}$.

In [23]:
def print_matrix(A):
    if A==None:
        print('\n')
    else:
        for i in range(len(A)):
            print(A[i])
        print('\n')
def create_identity_matrix(n):
    A=[]
    for i in range(0,n):
        temp=[]
        for j in range(0,n):
            if(i==j):
                temp.append(1)
            else:
                temp.append(0)            
        A.append(temp)
    return A
def inverse(A):
    
    #kiem tra neu ma tran A input khong hop le
    for i in range(0,len(A)):
        if len(A) != len(A[i]):
            print("Ma tran input khong vuong, khong the tim ma tran nghich dao!")
            return
    
    #tao ma tran In
    B=create_identity_matrix(len(A))
        
    
    flag=True
    k=0
    j=0
    
    ##duyet tung cot
    for i in range(0,len(A[0])):
        k=j
            
        flag=False
        
        #duyet tung dong cua cot do de kiem tra cot do co = 0 hay ko ?
        for l in range(j,len(A)):
            if A[l][i] != 0:
                flag=True
                
        if flag == True:
            if A[k][i] == 0:
                for z in (k+1,len(A)):
                    if A[z][i] != 0:
                        temp=A[k]
                        A[k]=A[z]
                        A[z]=temp
                        
                        temp=B[k] #cua B
                        B[k]=B[z] #cua B
                        B[z]=temp #cua B
                        break
            d=(1/A[k][i])
            for m in range(0,len(A[0])):
                A[k][m]=A[k][m]*d
                B[k][m]=B[k][m]*d #cua B
            
            for k1 in range (0,len(A)):
                if k1==i:
                    continue
                d=-A[k1][i]/A[k][i]
                for m in range(0,len(A[0])):
                    A[k1][m]=round(A[k1][m]+d*A[k][m],3) 
                    B[k1][m]=round(B[k1][m]+d*B[k][m],3) #cua B
            j=j+1
        else:
            print("Ma tran khong kha nghich")
            return
    return B


A=[[0,1,2],[1,2,1],[1,-1,3]] #kha nghich
print("Ma tran A: ")
for i in range(len(A)):
    print(A[i])
print("Ma tran nghich dao cua A: ")
A=inverse(A)
print_matrix(A)


B=[[1,3,-4],[1,5,-1],[3,13,-6]] #khong kha nghich
print("Ma tran B: ")
for i in range(len(B)):
    print(B[i])
print("Ma tran nghich dao cua B: ")
B=inverse(B)
print_matrix(B)
    

C=[[1,3,-4],[1,5,-1],[3,13,-6],[1,5,9]] #khong kha nghich
print("Ma tran C: ")
for i in range(len(C)):
    print(C[i])
print("Ma tran nghich dao cua C: ")
C=inverse(C)
print_matrix(C)

Ma tran A: 
[0, 1, 2]
[1, 2, 1]
[1, -1, 3]
Ma tran nghich dao cua A: 
[-0.875, 0.625, 0.375]
[0.25, 0.25, -0.25]
[0.375, -0.125, 0.125]


Ma tran B: 
[1, 3, -4]
[1, 5, -1]
[3, 13, -6]
Ma tran nghich dao cua B: 
Ma tran khong kha nghich


Ma tran C: 
[1, 3, -4]
[1, 5, -1]
[3, 13, -6]
[1, 5, 9]
Ma tran nghich dao cua C: 
Ma tran input khong vuong, khong the tim ma tran nghich dao!




In [2]:
## Mở rộng: Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả
import numpy as np
A = np.array([[0,1,2],[1,2,1],[1,-1,3]]) #kha nghich
B = np.array([[1,3,-4],[1,5,-1],[3,13,-6]]) #ko kha nghich
C = np.array([[1,3,-4],[1,5,-1],[3,13,-6],[1,5,9]]) # ko kha nghich

print("Ma tran A: ")
print(A)
print("Ma tran nghich dao cua A: ")
print(np.linalg.inv(A))

print("Ma tran B: ")
print(B)
print("Ma tran nghich dao cua B: ")
print(np.linalg.inv(B))

print("Ma tran C: ")
print(C)
print("Ma tran nghich dao cua C: ")
print(np.linalg.inv(C))

Ma tran A: 
[[ 0  1  2]
 [ 1  2  1]
 [ 1 -1  3]]
Ma tran nghich dao cua A: 
[[-0.875  0.625  0.375]
 [ 0.25   0.25  -0.25 ]
 [ 0.375 -0.125  0.125]]
Ma tran B: 
[[ 1  3 -4]
 [ 1  5 -1]
 [ 3 13 -6]]
Ma tran nghich dao cua B: 
[[-6.38009947e+15 -1.27601989e+16  6.38009947e+15]
 [ 1.12589991e+15  2.25179981e+15 -1.12589991e+15]
 [-7.50599938e+14 -1.50119988e+15  7.50599938e+14]]
Ma tran C: 
[[ 1  3 -4]
 [ 1  5 -1]
 [ 3 13 -6]
 [ 1  5  9]]
Ma tran nghich dao cua C: 


LinAlgError: Last 2 dimensions of the array must be square

Nhận xét:
- Đối với các ma trận khả nghịch, hàm inverse tự định nghĩa và hàm linalg.inv của thư viện numpy cho kết quả giống nhau
- Đối với ma trận không khả nghịch:
    + Hàm inverse tự định nghĩa sẽ thông báo ma trận không khả nghịch
    + Hàm linalg.inv của thư viện numpy cho ra một ma trận kết quả với các phần tử đều có giá trị vô cùng lớn/vô cùng bé
- Đối với ma trận không vuông:
    + Hàm inverse tự định nghĩa sẽ thông báo ma trận không vuông, không thể tìm ma trận nghịch đảo
    + Hàm linalg.inv của thư viện numpy sẽ thông báo lỗi chương trình

### Mô tả các hàm và ý tưởng thực hiện

1. Hàm print_matrix: dùng để in ra màn hình ma trận được truyền vào hàm
2. Hàm create_identity_matrix: dùng để tạo ra ma trận đơn vị cấp n
- Dùng hai vòng for lồng nhau để lần lượt thêm các giá trị 0 vào ma trận, trừ các phần tử trên đường chéo chính thì giá trị sẽ là 1
3. Hàm inverse: dùng để tìm ma trận nghịch đảo của một ma trận vuông cấp n
- B1: Đầu tiên, kiểm tra ma trận truyền vào có vuông hay không, nếu không vuông thì ngưng hàm
- B2: Nếu ma trận input là ma trận vuông cấp n, tiến hành khởi tạo một ma trận đơn vị B cấp n bằng hàm create_identity_matrix
- B3: Duyệt qua từng cột của ma trận input, nếu cột đang xét có phần tử nằm từ đường chéo chính trở xuống đều bằng 0 thì ngưng hàm, thông báo ma trận không khả nghịch, ngược lại thì thực hiện các bước sau:
    + Kiểm tra nếu phần tử nằm trên đường chéo chính bằng không thì hoán vị dòng chứa phần tử này với dòng có phần tử ở cột tương ứng khác 0 gần nhất với dòng đang xét. Việc này được thực hiện cùng lúc ở ma trận input và ma trận đơn vị B đã tạo ra trước đó.
    + Nhân dòng đang xét của ma trận input và dòng tương ứng của ma trận đơn vị B với 1/(phần tử ở đường chéo chính của ma trận input).
    + Cộng các dòng còn lại của ma trận input và cả ma trận đơn vị B (trừ dòng chứa phần tử nằm trên đường chéo chính) với một số thích hợp để biến các phần tử ở cột đang xét của ma trận input đều bằng 0.
    + Lặp lại B3
- B4: Ma trận đơn vị B được tạo ra ở B2 sau khi thực hiện cả 3 bước trên sẽ là ma trận nghịch đảo của ma trận input, hàm sẽ trả về ma trận B