Họ tên: Đàm Tử Tâm\
MSSV: 21120551\
Lớp: 21_2 (chính quy)\
Môn: Toán ứng dụng & thống kê

## Đồ án 3: Gram – Schmidt

1) Cho A là ma trận có thể phân rã QR. Sinh viên viết chương trình in ra ma trận Q và R, biết rằng A = QR.\
Lưu ý: sinh viên phải sử dụng thuật toán Gram – Schmidt đã được hướng dẫn trong phần bài tập. Sinh viên không được dùng các hàm có sẵn của các thư viện để phân rã QR.

2) Mở rộng:
- Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.
- Tìm hiểu và trình bày ứng dụng của QR decomposition

##### Quy định bài nộp
- Thực hiện toàn bộ bài làm trên 1 tập tin Jupyter Notebook (.ipynb)
- Đầu bài phải có phần trình bày thông tin sinh viên và giải thuật theo giống yêu cầu của Bài tập 18.
- Cuối bài phải có phần mô tả ý tưởng thực hiện và mô tả các hàm

##### Quy định chấm bài
Những trường hợp sau đây sẽ bị 0 điểm toàn bộ đồ án:
- Nộp sai quy định bài nộp
- Thực thi mã nguồn báo lỗi

LƯU Ý: SAO CHÉP BÀI LÀM CỦA NHAU SẼ BỊ 0 ĐIỂM TOÀN BỘ PHẦN THỰC HÀNH

## Giải thuật Gram – Schmidt để phân rã ma trận A = QR
- Bước 1: giả sử ma trận $A$ có n cột, từng cột của ma trận sẽ là các vector từ {$u_1,u_2,...u_n$}
- Bước 2: đặt $v_1 = u_1$, nếu $v_1$ là vector 0 thì họ không độc lập tuyến tính và kết thúc giải thuật
- Bước 3: đặt $v_2,v_3,...v_n$ lần lượt với $v_m = u_m − \sum_{i=1}^{m-1}\frac{⟨u_m, v_i⟩}{∥v_i∥^{2}}v_i$ (m từ 2 đến n). Nếu có bất kì vector $v_m$ nào là vector 0 thì họ không độc lập tuyến tính và kết thúc giải thuật
- Bước 4: xây dựng họ các vector trực chuẩn với $q_m = \frac{v_m}{∥v_m∥}$ (m từ 1 đến n). 
- Bước 5: xây dựng ma trận $Q$ gồm n cột, $Q(q_1,q_2,...,q_n)$
- Bước 6: xây dựng ma trận R là một ma trận tam giác trên, với
R = $\begin{bmatrix} ⟨u_1, q_1⟩ & ⟨u_2, q_1⟩ & ... & ⟨u_n, q_1⟩ \\
    0 & ⟨u_2, q_2⟩ & ... & ⟨u_n, q_2⟩ \\
    \vdots &\vdots & \ddots &\vdots\\               
    0 & 0 & ... & ⟨u_n, q_n⟩ \end{bmatrix}$

## Chương trình:

In [5]:
def multi_matrix(A,B):
    if(len(A[0])!=len(B)):
        print("Khong the nhan hai ma tran")
        return None
    C=[]
    temp=[]
    ans=0
    for i in range(len(A)):
        temp=[]
        for j in range(len(A[0])):
            ans=0
            for k in range(len(A[0])):
                ans=ans+A[i][k] * B[k][j]
            temp.append(round(ans,3))
        C.append(temp)
    return C
def print_matrix(A):
    for i in range(len(A)):
        print(A[i])
            
def subtract_vector(A,B):
    if(len(A)!=len(B)):
        return None
    C=[]
    for i in range(len(A)):
        C.append(A[i]-B[i])
    return C

def multi_vector_const(c,A):
    D=[]
    for i in range(len(A)):
        D.append(c*A[i])
    return D

def product(A,B):
    temp=0
    if(len(A)!=len(B)):
        return 0
    for i in range(len(A)):
        temp=temp+A[i]*B[i]
    return temp

def is_0_vector(A):
    for i in range(len(A)):
        if A[i]!=0:
            return False
    return True

def norm(A):
    temp=0.0
    for i in range(len(A)):
        temp=temp+A[i]**2
        
    return temp**(1/2)

def print_conclusion(A):
    if A==None: 
        return
    print("Ma tran A: ")
    print_matrix(A)
    print('\n')

    Q,R=qr_decomposition(A)
    if Q==None or R==None:
        return
    
    print("Ma tran Q: ")
    print_matrix(Q)
    print('\n')

    print("Ma tran R: ")
    print_matrix(R)
    print('\n')

    C=multi_matrix(Q,R)
    print("Ma tran QxR: ")
    print_matrix(C)
    print('\n')
    

def qr_decomposition(A):
    T=[]
    temp=[]
    for i in range(len(A[0])):
        for j in range(len(A)):
            temp.append(A[j][i]*1);
        T.append(temp)
        temp=[]
        
    Q=[]
    temp2=[]
    for i in range(len(T[0])):
        temp2.append(T[0][i]*1)
    Q.append(temp2)
    temp2=[]
    
    for i in range(1,len(T)):
        temp2=T[i]
        for j in range(0,len(Q)):
            temp=multi_vector_const(product(T[i],Q[j])/(norm(Q[j])**2),Q[j])
            temp2=subtract_vector(temp2,temp)
        if is_0_vector(temp2)==True:
            print("He vector khong doc lap tuyen tinh nen khong la ho truc giao")
            return None,None
        Q.append(temp2)
    
    #tinh truc chuan    
    for i in range(len(Q)):
        chuan1=norm(Q[i])
        for j in range(len(Q[0])):
            Q[i][j]=Q[i][j]/chuan1
    
    R=[]
    for i in range(len(Q)):
        temp=[]
        for j in range(len(T)):         
            if j<i:
                temp.append(0)
                continue
            temp.append(product(Q[i],T[j]))
        R.append(temp)
        
    Q1=[]
    temp=[]
    for i in range(len(Q[0])):
        for j in range(len(Q)):
            temp.append(Q[j][i]);
        Q1.append(temp)
        temp=[]
        
    return Q1,R
  
A=[[1,1,0],[-1,0,1],[0,1,1],[1,-1,0]] #co the phan ra QR
A1=[[1,0,1],[-1,1,1],[1,0,1],[-1,1,1]] #khong la ho truc giao -> ko phan QR
A2=[[1,-1,1],[4,2,5],[3,1,4]]

print("\n---------Test case 0---------")
print_conclusion(A)
print("\n---------Test case 1---------")
print_conclusion(A1)
print("\n---------Test case 2---------")
print_conclusion(A2)


---------Test case 0---------
Ma tran A: 
[1, 1, 0]
[-1, 0, 1]
[0, 1, 1]
[1, -1, 0]


Ma tran Q: 
[0.5773502691896258, 0.5773502691896258, 0.0]
[-0.5773502691896258, 0.0, 0.5773502691896256]
[0.0, 0.5773502691896258, 0.5773502691896256]
[0.5773502691896258, -0.5773502691896258, 0.5773502691896257]


Ma tran R: 
[1.7320508075688776, 0.0, -0.5773502691896258]
[0, 1.7320508075688776, 0.5773502691896258]
[0, 0, 1.1547005383792512]


Ma tran QxR: 
[1.0, 1.0, 0.0]
[-1.0, 0.0, 1.0]
[0.0, 1.0, 1.0]
[1.0, -1.0, -0.0]



---------Test case 1---------
Ma tran A: 
[1, 0, 1]
[-1, 1, 1]
[1, 0, 1]
[-1, 1, 1]


He vector khong doc lap tuyen tinh nen khong la ho truc giao

---------Test case 2---------
Ma tran A: 
[1, -1, 1]
[4, 2, 5]
[3, 1, 4]


Ma tran Q: 
[0.19611613513818404, -0.9434563530497265, -0.2672612419124319]
[0.7844645405527362, 0.3144854510165753, -0.5345224838248489]
[0.5883484054145521, -0.10482848367219207, 0.8017837257372704]


Ma tran R: 
[5.099019513592785, 1.9611613513818402, 6.47

 ## Mở rộng: tìm hiểu hàm/phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả

In [46]:
import numpy as np
np.set_printoptions(suppress=True)

def print_conclusion_np(A):
    if A==None: 
        return
    print("Ma tran A: ")
    print_matrix(A)
    print('\n')

    Q,R=np.linalg.qr(A)
   # if Q==None or R==None:
     #   return
    
    print("Ma tran Q: ")
    print_matrix(Q)
    print('\n')

    print("Ma tran R: ")
    print_matrix(R)
    print('\n')

    C=np.dot(Q,R)
    print("Ma tran QxR: ")
    print_matrix(C)
    print('\n')

A=[[1,1,0],[-1,0,1],[0,1,1],[1,-1,0]] #co the phan ra QR
A1=[[1,0,1],[-1,1,1],[1,0,1],[-1,1,1]] #khong la ho truc giao -> ko phan QR
A2=[[1,-1,1],[4,2,5],[3,1,4]]

print("\n---------Test case 0---------")
print_conclusion_np(A)
print("\n---------Test case 1---------")
print_conclusion_np(A1)
print("\n---------Test case 2---------")
print_conclusion_np(A2)


---------Test case 0---------
Ma tran A: 
[1, 1, 0]
[-1, 0, 1]
[0, 1, 1]
[1, -1, 0]


Ma tran Q: 
[-0.57735027 -0.57735027  0.        ]
[ 0.57735027 -0.         -0.57735027]
[-0.         -0.57735027 -0.57735027]
[-0.57735027  0.57735027 -0.57735027]


Ma tran R: 
[-1.73205081  0.          0.57735027]
[ 0.         -1.73205081 -0.57735027]
[ 0.          0.         -1.15470054]


Ma tran QxR: 
[ 1.  1. -0.]
[-1.  0.  1.]
[0. 1. 1.]
[ 1. -1.  0.]



---------Test case 1---------
Ma tran A: 
[1, 0, 1]
[-1, 1, 1]
[1, 0, 1]
[-1, 1, 1]


Ma tran Q: 
[-0.5        -0.5         0.52696519]
[ 0.5        -0.5         0.47149517]
[-0.5        -0.5        -0.52696519]
[ 0.5        -0.5        -0.47149517]


Ma tran R: 
[-2.  1.  0.]
[ 0. -1. -2.]
[ 0.  0. -0.]


Ma tran QxR: 
[1. 0. 1.]
[-1.  1.  1.]
[ 1. -0.  1.]
[-1.  1.  1.]



---------Test case 2---------
Ma tran A: 
[1, -1, 1]
[4, 2, 5]
[3, 1, 4]


Ma tran Q: 
[-0.19611614  0.94345635 -0.26726124]
[-0.78446454 -0.31448545 -0.53452248]
[-0.5883

**Nhận xét:** tạm gọi ma trận $Q, R$ nhận được từ hàm qr_decomposition là $Q, R$; ma trận $Q, R$ nhận được từ hàm linalg.qr của như viện numpy là $Q_1, R_1$
- Hàm qr_decomposition và hàm linalg.qr của như viện numpy lần lượt trả về ma trận $Q, R$ và $Q_1, R_1$ được phân rã từ ma trận A với ma trận $Q_1=-Q$, $R_1=-R$. Tuy nhiên, việc này không ảnh đến kết quả do khi thực hiện $QR = Q_1 R_1 = A$
- Đối với hàm qr_decomposition, do thực hiện theo giải thuật Gram - Schmidt nên khi thực hiện bước trực giao hóa các vector cột của ma trận A nếu có xuất hiện vector sau khi trực giao hóa là vector 0 thì sẽ kết thúc giải thuật, dẫn đến không thể phân rã ma trận A thành ma trận $Q, R$ và trả về 2 kết quả None. Tuy nhiên, ở hàm linalg.qr của như viện numpy vẫn có thể giải quyết vấn đề này và cho ra kết quả trả về là 2 ma trận $Q_1, R_1$ được phân rã từ ma trận A

## Mở rộng: tìm hiểu và trình bày ứng dụng của QR decomposition
Phân tích QR (QR decomposition) là một phương pháp phân tích ma trận trong đại số tuyến tính cho phép chia một ma trận bất kỳ thành tích của hai ma trận, một ma trận Q là một ma trận Orthogonal và một ma trận R là ma trận tam giác trên.

Phân tích QR là một công cụ rất hữu ích và được dùng phổ biến trong toán học, khoa học máy tính và các lĩnh vực khác. Một số ví dụ về ứng dụng của QR decomposition như sau:

- Giải hệ phương trình tuyến tính: Một trong những ứng dụng chính của phân tích QR là giải hệ phương trình tuyến tính. Vì ma trận R là ma trận tam giác trên, việc giải hệ phương trình sẽ dễ dàng hơn.

- Tìm trị riêng và vectơ riêng: Với phân tích QR, ta có thể tính toán trị riêng và vectơ riêng của một ma trận bằng cách sử dụng phương pháp QR algorithm.

- Tính toán đa thức: Phân tích QR có thể được sử dụng để tính toán đa thức của một ma trận.

- Giảm chiều dữ liệu: Phân tích QR cũng có thể được sử dụng để giảm chiều dữ liệu, trong đó ma trận Q có thể được sử dụng để ánh xạ dữ liệu vào một không gian chiều thấp hơn.

- Giải các bài toán tối ưu: Phân tích QR có thể được sử dụng để giải các bài toán tối ưu, bao gồm cả bài toán tối ưu tuyến tính và phi tuyến tính.

## Mô tả các hàm và ý tưởng thực hiện

### Các hàm trong chương trình chính (không dùng thư viện):
**1. multi_matrix:** Hàm nhân hai ma trận, với input là ma trận A và B, nếu số cột của A khác số dòng của B thì kết thúc hàm (không thể nhân). Ngược lại, thực hiện 3 vòng for lồng nhau để nhân ma trận và trả về ma trận sau khi nhân A và B.\
**2. print_matrix:** Hàm in một ma trận, với input là ma trận cần in.\
**3. subtract_vector:** Hàm trừ hai vector, với input là vector A và vector B, ếu số phần tử của 2 vector khác nhau thì kết thúc hàm (không thể trừ). Ngược lại, thực hiện A - B và trả về vector sau khi thực hiện A - B.\
**4. multi_vector_const:** Hàm nhân một vector với một hằng số, với input là hằng số c và vector A, trả về vector sau khi thực hiện c * A\
**5. product:** Hàm tính tích vô hướng chính tắc của hai vector, với input là vector A và vector B, nếu số phần tử của hai vector khác nhau thì ngưng hàm, trả về 0. Ngược lại, trả về tích vô hướng chính tắc của hai vector.\
**6. is_0_vector:** Hàm kiểm tra một vector có là vector 0 không, nếu phải, trả về True, ngược lại trả về False\
**7. norm:** Hàm tính chuẩn của một vector, với input là vector A cần tính chuẩn, trả về chuẩn của vector A\
**8. print_conclusion:** Hàm in kết quả chạy test cho chương trình chính (không dùng thư viện), với input là ma trận A, hàm sẽ in ra ma trận A. Nếu có thể phân rã ma trận A thành ma trận Q, R bằng hàm qr_decomposition (hàm này dùng thuật giải Gram – Schmidt), hàm sẽ in ra cả ma trận Q, ma trận R và ma trận QxR (tính bằng hàm multi_matrix) để kiểm tra lại kết quả (QxR = A). Ngược lại, nếu không thể phân rã ma trận A thành ma trận Q, R bằng thuật giải Gram – Schmidt thì thông báo và ngưng hàm.\
**9. qr_decomposition:** Hàm phân rã QR ma trận A bằng giải thuật Gram – Schmidt, với input là ma trận A có n cột
- Đầu tiên, lưu n vector cột của A vào T, tương ứng là ${u_1, u_2,..., u_n}$ trong bước 1 của giải thuật
- Lưu $v_1 = u_1$, đưa vào Q
- Tính $v_2,v_3,...v_n$ lần lượt với $v_m = u_m − \sum_{i=1}^{m-1}\frac{⟨u_m, v_i⟩}{∥v_i∥^{2}}v_i$ (m từ 2 đến n). Chạy một vòng for i để duyệt từ T[1] đến T[n-1] tương ứng với $u_2,u_3,...u_n$. Với mỗi $u_m$ (T[i]), lưu $u_m$ vào temp2. Lồng thêm một vòng for j phía trong vòng for i ở trên để duyệt tương ứng từ $v_1, v_2,..., v_{m-1}$. Mỗi lần vòng for j chạy, tính $\frac{⟨u_m, v_j⟩}{∥v_j∥^{2}}v_j$ bằng cách kết hợp các hàm multi_vector_const, product, norm và kết hợp các phép toán rồi lưu vào temp, sau đó lấy temp2 - temp. Sau khi vòng for j chạy xong với mỗi i, ta được $v_m = u_m − \sum_{i=1}^{m-1}\frac{⟨u_m, v_i⟩}{∥v_i∥^{2}}v_i$. Kiểm tra nếu $v_m$ là vector 0 bằng hàm is_0_vector thì thông báo họ không độc lập tuyến tính và kết thúc giải thuật và trả về None, None. Ngược lại, đưa $v_m$ vào Q.
- Tính trực chuẩn của mỗi vector trực giao trong Q: Chạy một vòng for i duyệt qua từng vector trong Q và tính chuẩn của Q[i] bằng hàm norm rồi lưu vào chuan1. Chạy thêm một vòng for j lồng trong vòng for i duyệt qua từng phần tử của vector Q[i] và lấy Q[i][j]/chuan1.
- Tạo ma trận R: Chạy một vòng for i duyệt qua từng vector của Q (các vector trực chuẩn), tạo thêm một vòng for j lồng trong i duyệt qua từng vector của T (các vector cột của ma trận input), nếu j<i thì R[i][j] = 0, ngược lại R[i][j] sẽ là tích vô hướng chính tắc của Q[i] và T[j] (tính bằng hàm product). Sau bước này ta được ma trận R trong phân rã QR
- Tạo ma trận Q: Tạo Q1 lưu ma trận chuyển vị của ma trận Q hiện có, ta được ma trận Q1 là ma trận Q trong phân rã QR .
- Trả về ma trận Q1, R tương ứng ma trận Q, R sau khi phân rã QR ma trận A

Khi test chương trình chính (không dùng thư viện), sẽ chạy hàm print_conclusion

### Các hàm trong chương trình mở rộng (dùng thư viện):

**print_conclusion_np:** Hàm in kết quả chạy test cho chương trình mở rộng (dùng thư viện), với input là ma trận A, hàm sẽ in ra ma trận A. Sau đó phân rã ma trận A thành ma trận Q, R bằng hàm linalg.qr của thư viện numpy rồi in ra ma trận Q và ma trận R. Thực hiện QxR bằng hàm dot của thư viện numpy và in ra để kiểm tra QxR=A

Khi test chương trình mở rộng (dùng thư viện), sẽ chạy hàm print_conclusion_np